#!/usr/bin/env python3
"""
Toxic Terminator - Setup Check Utility
======================================

This script helps users verify that all required dependencies and model files
are correctly installed and available for the Toxic Terminator application.

The utility performs the following checks:
1. Ensures all required Python packages are installed
2. Verifies the existence of necessary model files
3. Downloads required NLTK resources if they're missing
4. Provides guidance for fixing any detected issues

Usage:
    python setup_check.py

Author: Venom
Date: 2023
"""

import sys
import importlib
import subprocess
import os

def check_package(package_name):
    """
    Check if a Python package is installed and available.
    
    Args:
        package_name (str): Name of the package to check
        
    Returns:
        bool: True if package is installed, False otherwise
    """
    try:
        # Attempt to import the package to verify it's installed
        importlib.import_module(package_name)
        return True
    except ImportError:
        # Return False if import fails, indicating package is not installed
        return False

def main():
    """
    Main function that performs all setup verification checks and reports results.
    
    This function:
    1. Checks for required Python packages
    2. Verifies model files exist
    3. Ensures NLTK resources are downloaded
    4. Provides installation instructions for any missing components
    """
    # List of required Python packages for the application
    required_packages = [
        "streamlit",  # Web interface framework
        "nltk",       # Natural Language Toolkit for text processing
        "sklearn",    # Machine learning library (scikit-learn)
        "pandas",     # Data manipulation and analysis
        "numpy"       # Numerical computing
    ]
    
    # List of required NLTK resources for text processing
    nltk_resources = [
        "punkt",                    # Tokenizer for splitting text into words
        "wordnet",                  # Lexical database for word meanings
        "averaged_perceptron_tagger", # Part-of-speech tagger
        "stopwords"                 # Common words to filter out
    ]
    
    print("Checking required packages...")
    missing_packages = []
    
    # Check each required package and report status
    for package in required_packages:
        if check_package(package):
            print(f"✅ {package} is installed")
        else:
            print(f"❌ {package} is NOT installed")
            missing_packages.append(package)
    
    # Check for the existence of required model files
    print("\nChecking required model files...")
    model_files = ["models/toxicity_model.pkt", "models/tf_idf.pkt"]
    missing_files = []
    
    for file in model_files:
        if os.path.exists(file):
            print(f"✅ {file} exists")
        else:
            print(f"❌ {file} does NOT exist")
            missing_files.append(file)
    
    # Check for NLTK resources and download any that are missing
    print("\nChecking NLTK resources...")
    import nltk
    
    for resource in nltk_resources:
        try:
            # Check if resource exists based on resource type
            if resource == 'punkt':
                nltk.data.find(f'tokenizers/{resource}')
            else:
                nltk.data.find(f'corpora/{resource}')
            print(f"✅ NLTK {resource} is downloaded")
        except LookupError:
            # If resource is missing, download it automatically
            print(f"❌ NLTK {resource} is NOT downloaded")
            print(f"   Downloading NLTK {resource}...")
            nltk.download(resource)
    
    # Provide summary and recommendations for fixing issues
    if missing_packages:
        print("\n⚠️ Some packages are missing. Install them with:")
        print(f"pip install {' '.join(missing_packages)}")
    
    if missing_files:
        print("\n⚠️ Some model files are missing. Make sure the Toxic Terminator model files are in the current directory.")
        print("   These files should be generated by running the model.ipynb notebook.")
    
    if not missing_packages and not missing_files:
        print("\n✅ All dependencies are satisfied. You can run the Toxic Terminator with:")
        print("streamlit run app.py")

if __name__ == "__main__":
    # Execute the main function when script is run directly
    main()